# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 842b739cf03b1674f5f7379449c35dc5e198a041f8d19bfb75160b370119fcfab4bf44d881c9d3b908a64e07a14ec4a01a74813b15805d53b356f399db4b5f86

test:
  secret_key_base: 3d73684330548c2e26517981eabe8712696e57cb62652caf69868377a3d614385218161785d68489cab7ef57e002b4602dda037c9c021032659bb3aa76b4d90e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
